name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
#      - name: Set up JDK 1.11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.11
#
#      - name: setup Database
#        run: docker-compose up -d 
#
#      - name: pause
#        run: sleep 30
        
      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true
        
      # make dir for badges
      - name: badges branch and make dir
        run: |
          git checkout badges || git checkout -b badges
          mkdir -p .github/badges
            
      # make points badge
      - name: points badge
        uses: emibcn/badge-action@v1
        with:
          LABEL: 'Points'
          STATUS: ${{ steps.autograder.outputs.Points }}
          COLOR: cyan
          path: '.github/badges/points.svg'

          # - name: Upload badge as artifact
          #   uses: actions/upload-artifact@v2
          #   with:
          #     name: badge
          #     path: '.github/badges/points.svg'
          #     if-no-files-found: error
          
       
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
         github_token: ${{github.token}}
         soft_fail: true
         branches: badges

      # commit and push badge if score has changed
      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges/points.svg'
          git commit -m "Add/Update badge"
        continue-on-error: true
        
      - name: Push badge commit
        uses: ad-m/github-push-action@v0.6.0
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges

      # fail job if autograder returns failed
      # outcome can be 'success', 'failure', 'cancelled', or 'skipped'
      # trigger fail either on !success or on failure depending on preference
      - name: check autograder pass fail
        if: ${{ steps.autograder.outcome != 'success' }}
        # if: ${{ steps.autograder.outcome == 'failure' }}
        # if: ${{ failure }}
        run: exit 1
